site_name: Ithkuil
site_url: https://glekwille.lojban.pw
plugins:
    - search
    - minify:
        minify_html: true
nav:
    - Preface: index.md
    - Basic: basic.md
    - Cases: cases.md
    - Verbs: verbs.md
    - Metalinguistic: metalinguistic.md
    - Text structure: text-structure.md
    - Suffixes: suffixes.md
    - Syntax: syntax.md

extra_css: ['css/extra.css']

markdown_extensions:
  - admonition
  - meta
  - codehilite:
      guess_lang: false
  - toc:
      permalink: "#"
      baselevel: 1
theme:
    feature:
        tabs: true
        instant: true
    name: material
    custom_dir: 'theme'
    palette:
        primary: red
        accent: amber
    favicon: 'img/favicon.ico'
    icon:
        logo: material/library
    highlightjs: false
    show_sidebar: true

docs_dir: src
site_dir: docs

extra:
  social:
    - icon: fontawesome/brands/discord
      link: 'https://discord.gg/arXJQPe'
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/lagleki/glekwille/issues'
    - icon: fontawesome/brands/reddit
      link: 'https://reddit.com/r/ithkuil'

